### ISSUE TITLE
io.grpc.StatusRuntimeException: CANCELLED: Failed to read message.

### ISSUE THREAD

**Issue by huan** [wechaty/scala-wechaty#1]
After started as the README described, I send a `#ding` to the bot, but did not get any response from the bot.

After a while, the following exception displayed:

```sh
[grpc-default-executor-0 INFO]22:45:20  hostie.PuppetHostie PuppetHostie MessagePayload([8432552652961657162])
#ding
[grpc-default-executor-0 INFO]22:45:20  hostie.PuppetHostie PuppetHostie messageSendText(%s, %s)

[grpc-default-executor-0 ERROR]22:46:21  hostie.PuppetHostie Grpc onError
io.grpc.StatusRuntimeException: CANCELLED: Failed to read message.
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:447)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInternal(ClientCallImpl.java:611)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:584)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: io.grpc.StatusRuntimeException: INTERNAL: can not get message callback response.
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:240)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:221)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:140)
	at io.github.wechaty.grpc.PuppetGrpc$PuppetBlockingStub.messageSendText(PuppetGrpc.java:2934)
	at wechaty.hostie.MessageSupport.messageSendText(MessageSupport.scala:41)
	at wechaty.hostie.MessageSupport.messageSendText$(MessageSupport.scala:35)
	at wechaty.hostie.PuppetHostie.messageSendText(PuppetHostie.scala:13)
	at wechaty.user.Message.say(Message.scala:13)
	at wechaty.DingDongBot$.$anonfun$main$3(DingDongBot.scala:26)
	at wechaty.DingDongBot$.$anonfun$main$3$adapted(DingDongBot.scala:21)
	at wechaty.Wechaty.$anonfun$toMessage$1(Wechaty.scala:65)
	at wechaty.Wechaty.$anonfun$toMessage$1$adapted(Wechaty.scala:65)
	at wechaty.puppet.events.EventEmitter$.$anonfun$emit$1(EventEmitter.scala:23)
	at wechaty.puppet.events.EventEmitter$.$anonfun$emit$1$adapted(EventEmitter.scala:22)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at wechaty.puppet.events.EventEmitter$.emit(EventEmitter.scala:22)
	at wechaty.hostie.GrpcEventSupport.onNext(GrpcEventSupport.scala:44)
	at wechaty.hostie.GrpcEventSupport.onNext$(GrpcEventSupport.scala:21)
	at wechaty.hostie.PuppetHostie.onNext(PuppetHostie.scala:13)
	at wechaty.hostie.PuppetHostie.onNext(PuppetHostie.scala:13)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:434)
	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInternal(ClientCallImpl.java:599)
	... 6 more
```

**Comment by jcai** [comment]
> Caused by: io.grpc.StatusRuntimeException: INTERNAL: can not get message callback response.
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:240)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:221)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:140)
	at io.github.wechaty.grpc.PuppetGrpc$PuppetBlockingStub.messageSendText(PuppetGrpc.java:2934)



貌似是远端的rpc服务器出现问题了  发送完消息，远端服务器没有返回数据

**Comment by huan** [comment]
Yes, you are right. The server is not working as expected.

I saw the following log message from the server, it seems that you did not provide the first argument to the `messageSendText()`:

> 23:10:27 VERB PuppetDonut messageSendText("", dong, )

If the first argument is empty, then there must be wrong at somewhere in the client code.

```sh
23:10:27 VERB PuppetServiceImpl messageSendText()
23:10:27 VERB PuppetDonut messageSendText("", dong, )
23:10:27 VERB Donut(ffi-adapter) SendWeChatData(1,{"data":{"content":"dong","to_wxid":""},"type":11036})
23:11:27 ERR PuppetServiceImpl grpcError() messageSendText() rejection: can not get message callback response.
{ code: 13, details: 'can not get message callback response.' }
```

**Comment by huan** [comment]
I have just confirmed that the code can reply `dong` in Room.

But if we are sending a direct message, then the `conversationId` will not be set correctly.

Thanks for your great Scalar work for Wechaty, it's amazing that we have support one more language for our Multi-language Wechaty project!

Link to https://github.com/wechaty/wechaty/issues/1927

**Comment by jcai** [comment]
https://github.com/jcai/scala-wechaty/blob/c4140cf60345e0e4ff0627712494e6de6ace7b31/wechaty-hostie/src/main/scala/wechaty/hostie/MessageSupport.scala#L29

测试后发现，服务器返回的fromid是空字符串。

**Comment by huan** [comment]
I'd like to suggest that we should check the scala code because the TS version can work without any problem.

**Comment by jcai** [comment]
因为js里面判断空字符串是false java语言是判断null  我已经改了，不过从程序设计角度来看，如果没有值，最好返回null而不是""

**Comment by huan** [comment]
Yes, you are right and I fully agree with you.

It would be great if you can file an issue at https://github.com/chatie/grpc/issues so that we can investigate it in the future, thanks!
